### ISSUE TITLE
Can i use core 0.6.2 with doctrine-dbal 0.2.2 ?

### ISSUE THREAD

**Issue by eddycharly** [auxmoney/OpentracingBundle-Doctrine-DBAL#12]
https://github.com/auxmoney/OpentracingBundle-Doctrine-DBAL/blob/1edab8d8b4ac9275a639abf5477631dcff6e5a09/composer.json#L20

@cawolf Sorry if this is a stupid question but is it possible to use core 0.6.2 with doctrine-dbal 0.2.2 ?

**Comment by cawolf** [comment]
No, not yet - I will try to provide PRs for all plugins asap.

**Comment by eddycharly** [comment]
👍
