### ISSUE TITLE
[BC Break] 2.10.1 to v2.10.2: PDOStatement::convertParamType() must be of the type int, null given

### ISSUE THREAD

**Issue by noniagriconomie** [auxmoney/OpentracingBundle-Doctrine-DBAL#15]
Hello

I am opening an issue on this repo due to this one https://github.com/doctrine/dbal/issues/3976

We do have a **bc break behaviour** when upgrading **doctrine/dbal** from **2.10.1 to v2.10.2**

**But it occurs only** when this bundle is enabled, otherwise code works fine

Do you know what can be the reason?

Many thanks

**Comment by cawolf** [comment]
Hi @noniagriconomie, 

I will try to reproduce this behaviour locally and give you feedback on the cause of the problem asap.

**Comment by cawolf** [comment]
I can reproduce it. We will update our dependencies to at least `doctrine/dbal` version `^2.7` and fix some type hints and doc blocks.

**Comment by noniagriconomie** [comment]
@cawolf thank you for your time checking this :)
if you create a PR, may I ask you to ping me so that i can help you/check it on our code base as well before releasing

let me know,

**Comment by cawolf** [comment]
@noniagriconomie PR is up and ready, if you wanna have a look at it. We will probably merge tomorrow.

**Comment by noniagriconomie** [comment]
hi @cawolf i will check today, thank you
