### ISSUE TITLE
Could you expose the inner statement ?

### ISSUE THREAD

**Issue by eddycharly** [auxmoney/OpentracingBundle-Doctrine-DBAL#6]
https://github.com/auxmoney/OpentracingBundle-Doctrine-DBAL/blob/853dd73ba0ae0f994f5af018668f415d44e91a60/DBAL/TracingStatement.php#L19

We would need to access the inner statement, as our code sometimes depends on the statement being a PDOStatetment.

Would it be ok to introduce a method to give access to the underlying statement ?

Of course the calls made directly to the underlying statement won't be traced.

**Comment by cawolf** [comment]
Sure, it will make it to the initial release.

**Comment by eddycharly** [comment]
thanks 👍
