### ISSUE TITLE
Factory initiates the connection instead of just creating it

### ISSUE THREAD

**Issue by eddycharly** [auxmoney/OpentracingBundle-Doctrine-DBAL#8]
Here the call to `$connection->getWrappedConnection()` initiates the connection, whereas the factory should only create it :

https://github.com/auxmoney/OpentracingBundle-Doctrine-DBAL/blob/b7464333dc6067cb1bb34497e2dfc0a9d23a93c6/DBAL/TracingConnectionFactory.php#L46-L51

This is an issue as a code creating a connection with invalid params should be safe until it uses it.
With this implementation it's not the case anymore, the `createConnection` method should delay connection later.

Here is the code of doctrine that initiates the connection :
https://github.com/doctrine/dbal/blob/01143c9cd4fc360a6e42017902fd9b591ca706bb/lib/Doctrine/DBAL/Connection.php#L1230-L1237

**Comment by eddycharly** [comment]
I'm going to open a PR if it's ok for you

**Comment by cawolf** [comment]
Hi @eddycharly ,

sure, it reads like an improvement. I was curious about your approach, because we stumbled upon this exact same question during the initial development.

Right now, I would try to understand the root problem you are trying to solve. Did I understand you correctly that  during the lifetime of a request, the connection factory is creating connections with invalid credentials and then fixes these credentials before actually connecting to a database? If not, could you please elaborate the exact problem for me again?

**Comment by eddycharly** [comment]
The initial problem is related to the our ci pipelines.

At some point we run tests with a sort of fake set of parameters, some of these parameters are not technically incorrect, but the tests are run in a network that doesn't allow a connection to the database.

We know that the connection won't be used by our tests so it's not really a problem because the connection is never initiated (if it was the test would fail).

Now i integrated the opentracing dbal bundle, the tests are failing.

I could take time to find a solution in our code but i feel like the behavioral change introduced by the opentracing dbal bundle is annoying, i would prefer that the bundle is transparent in regards to the connection initiation.

Just my feeling but that sounds not a good strategy to change the way dbal behaves here.

**Comment by cawolf** [comment]
You are completely right, the early connect would also blow our smoke tests in our CI. Thank you for the clarification, this ticket is more than valid. Let's see if we can find a solution in the PR.

**Comment by eddycharly** [comment]
Great, thanks.

I have to say i really love your work and responsiveness.
Even if i don't know much about php it's a pleasure to collaborate with you.
